amida-tech/amida-auth-microservice

- README.md
- config/express.js
- config/param-validation.js
- config/passport.js
- package.json
- server/controllers/auth.controller.js
- server/routes/auth.route.js
- server/tests/integration/auth.integration.spec.js
- yarn.lock
Allows users to make password updates via a protected endpoint. This endpoint is protected with Passport JWT for Bearer auth. The repo includes documentation for how to implement this strategy for your own services, in order to integrate with the auth service.
SER-7, SER-8
You can use the following cURL commands to create a user, authenticate, and submit a password change. You should then try re-authenticating with the new password.
```curl
curl -X "POST" "http://localhost:4000/api/user" \
-H "Content-Type: application/json; charset=utf-8" \
-d $'{
"email": "test@amida.com",
"username": "test123",
"password": "testpass"
}'
curl -X "POST" "http://localhost:4000/api/auth/login" \
-H "Content-Type: application/json; charset=utf-8" \
-d $'{
"username": "test123",
"password": "testpass"
}' …
```
> Password updates and Bearer auth instructions

- config/param-validation.js
- package.json
- server/controllers/user.controller.js
- server/models/user.model.js
- server/routes/auth.route.js
- server/routes/user.route.js
- server/tests/integration/user.integration.spec.js
- yarn.lock
Allows users to create OAuth-style scope arrays for permissions embedded in JWT. Sets up middleware for the microservice to validate admin functionality, which serves as an example of how to validate scopes in other services.
SER-10, SER-43
Create a user with `admin` scope. Make sure this user can update user scopes, as this is an admin-protected function. The workflow is demonstrated in the test code.
> Add scopes, scope modification, and scope validation

- server/controllers/user.controller.js
- server/models/user.model.js
- server/tests/integration/user.integration.spec.js
- server/tests/models/user.model.spec.js
Remove password and salt in API responses. This is unnecessary and presents a security risk.
SER-67
Perform any `/user` API call. Confirm that only id, username, email, and scopes are present on the response object.
> hide password and salt in API responses

- server/controllers/user.controller.js
- server/models/user.model.js
- server/routes/user.route.js
- server/tests/integration/user.integration.spec.js
- server/tests/models/user.model.spec.js
- user updates require either yourself or admin to be logged in
SER-51
Create a user and an admin user. Log in as the non-admin user. You should be able to PUT to update your own email. Try to update the admin user's email. It should fail. Not log in as the admin user. You should be able to update the email of both users.
> add user update and isAdmin checks

- .env.example
- .gitignore
- Dockerfile
- README.md
- config/config.js
- config/passport.js
- server/controllers/auth.controller.js
- server/models/user.model.js
- server/tests/integration/auth.integration.spec.js
Allow JWT signing and verification with RSA, rather than HMAC.
SER-66
First, set JWT_MODE to `rsa` in `.env`. Then, generate a keypair according to the README. You should be able to run the API manually, as well as run the test harness. Make sure the public/private key path variables are set to match whatever keys you create.
Additionally, if you have a service that integrates with the auth service, you can now set the `.verify` function calls to use the `RS256` algorithm and use the public key in place of the shared secret. See `config/passport.js` to see how the auth service does it internally.
> JWT Public Key

- README.md
Add instructions to the README for creating sample JWTs. In some cases, a developer may want to test another service that will eventually authenticate against the Amida Auth service, but without actually using an instance of the Auth service. We provide directions for using jwt.io to create dummy tokens to the requirements of the Auth service.
SER-73
Select a secondary service, such as messaging or surveys. Create a token by following the instructions in the README. Make sure that the appropriate protected routes can be accessed in unit tests using this token.
> add README instructions for generating a test token

- README.md
- config/passport.js
If you start your app without the `FACEBOOK_*` env vars, it won't crash. It's now clear from implementation how to add a new external provider strategy without breaking env compatibility.
> app doesn't crash when started without facebook env vars

- server/controllers/user.controller.js
- server/tests/integration/user.integration.spec.js
Missing email lookup now properly returns 404.
> return 404 on missing email lookup

- config/param-validation.js
- package.json
- server/helpers/owasp.js
- server/routes/auth.route.js
- server/routes/user.route.js
- server/tests/integration/auth.integration.spec.js
- server/tests/integration/common.spec.js
- server/tests/integration/user.integration.spec.js
- yarn.lock
Adds OWASP password validation to all password-related routes. The checking is done by a middleware function before controllers are called.
https://jira.amida-tech.com/browse/RR-808
Create a new user, update a password, and reset a password. In all of these stages, passwords must meet OWASP standards.
Middleware is configured to enforce 2/3 of: uppercase, number, and special character.
> add OWASP password strength test

- server/helpers/mailer.js
Constructs the url for the password-reset interface from the requester's origin.
This is a lightweight solution and does not check the origin against any environment variable or whitelist. I can think of an attack is if someone creates a spoof of a client site, manages to get a user on myfakeindaba.com and go through the forgot password flow with their client domain, and passes the password the users sets to their own backend as well. Or they can just post to `reset-password` with a known user's email and their spoof host in the origin header, and hope the user follows the link and resets and leaks their new password there.
If I'm right about that vulnerability, we may have to consider putting the client host in an environment variable, either just for the `reset-password` url, or for the …
> SER-174 Use requesting origin for reset password links in email

- config/param-validation.js
- config/passport.js
- config/sequelize.js
- package.json
- server/controllers/auth.controller.js
- server/models/refreshToken.model.js
- server/models/user.model.js
- server/routes/auth.route.js
- server/tests/integration/auth.integration.spec.js
- yarn.lock
Add refresh token endpoints and behavior.
[SER-186](https://jira.amida-tech.com/browse/SER-186)
First, make sure the test harness runs.
Then, you will want to mimic the client workflow. Log in normally. You should set the normal auth token to have a short expiration time. When the token expires, confirm that you can use the reset token endpoint `POST /token` to get a new, valid JWT.
This behavior will be handled by clients. If they receive a 401 based on an expired token, they should call the `/token` endpoint then resubmit the 401. @mhiner can confirm that this is the correct design or correct me if I am wrong.
There is also an endpoint `POST /token/reject` that will expire your current refresh token. The JWT token will still be valid, but the only way to get a new refresh token is to …
> add refresh token functionality

- .circleci/config.yml
- .env.example
- config/config.js
- kubernetes.yml
- server/helpers/mailer.js
Before the fix:
MAILER_EMAIL_ID was used both as the username/email used to login to the service specified by MAILER_SERVICE_PROVIDER, and as the "from" email address on the automated email.
This does not work with certain service providers such as mailgun, which requires/sets up a different email address than the one associated with the account to send emails from.
The fix:
Add env var MAILER_FROM_EMAIL_ADDRESS and change the call to nodemailer to use this for he from address.
* [SER-214](https://jira.amida-tech.com/browse/SER-214)
1. Set the MAILER_ env vars (thorough description and examples of how to set them in README.md).
2. If using the orange app, on the login screen, click the "I forgot my password button" and enter your email address. You should receive a password reset email …
> SER-214 Customizable Mailer From Email Address

- config/param-validation.js
- server/controllers/auth.controller.js
- server/tests/integration/auth.integration.spec.js
As suggested in Orange-707, this adds a current password check to the `update-password` endpoint.
If the current password isn't correct, it returns a 403 forbidden.
if the current password is correct, it works as normal.
https://jira.amida-tech.com/browse/ORANGE-707
Via postman:
* login as a valid user
* include your token in the following requests
* POST to the update-password endpoint with a body a la
```
{
oldPassword: 'wrong',
password: 'Newpass1!'
}
```
> this should fail with a 403
* POST to the update-password endpoint with a body a la
```
{
oldPassword: 'CorrectPasswordForTheLoggedInUser',
password: 'Newpass1!'
}
```
> this should succeed like before
When an attacker finds a user session that was left …
> requiring old password to allow updating password

- .dockerignore
- .env.example
- .env.production
- README.md
- config/config.js
- server/controllers/auth.controller.js
- server/helpers/mailer.js
See the Jira ticket.
[ORANGE-478](https://jira.amida-tech.com/browse/ORANGE-478)
Set env var `AUTH_MICROSERVICE_URL`
Set the `AUTH_SERVICE_MAILER_...` env vars
Use a client such as the orange app's "forgot password?" functionality.
You should get an email and in that email the password reset link should be `{whatever you set your AUTH_MICROSERVICE_URL to}/reset-password/{the token}`
Nope.
In the following case, I set `AUTH_MICROSERVICE_URL=http://localhost:4000/api/v1`:
> Orange 487 Make password rest URI configurable via env var

- .env.example
- .env.production
- README.md
- config/config.js
- config/winston.js
- index.js
Makes the winston logging level configurable via the `LOG_LEVEL` environment variable.
[ORANGE-852](https://jira.amida.com/browse/ORANGE-852)
1. Set your `LOG_LEVEL` in your `.env` file to any valid winston level (see winston documentation or the code below for valid levels)
2. Add these lines to any file (`index.js` would work nice).
```js
logger.error('this is error');
logger.warn('this is warn');
logger.info('this is info');
logger.verbose('this is verbose');
logger.debug('this is debug');
logger.silly('this is silly');
```
3. `yarn start` and ensure you only see print the statements of the level you set and levels below it. Ex, if `LOG_LEVEL=info`, you should only see print:
```sh
this is error
this is warn
this is info
```
4. Repeat the same process without `LOG_LEVEL` defined, and …
> Make log level configurable via env var

- .dockerignore
- Dockerfile
Enables DB migrations (and undos) to be run by the docker image.
Previously, not all the files necessary for migrations to run were run were copied in the Dockerfile from the builder image to the runner image.
The ticket for this PR is
https://jira.amida.com/browse/ORANGE-903
The technical debt cleanup ticket for later is
https://jira.amida.com/browse/ORANGE-904
1. Docker build this version of the code.
```sh
cd /your/auth-service/git/repo/dir
git checkout this-version-of-the-code
docker build -t some/image:version .
```
2. Run the docker image properly using `docker run` (see README.md)
3. Login to the image using `docker exec -it your-image-name /bin/bash`
4. Run the migration:
WARNING: only do the following on a DB you don't care about potientially having to blow away.
`yarn migrate` …
>  hotfix/enable-docker-image-to-run-migration

- config/express.js
Fixes a 500 return when supplying invalid credentials 
https://jira.amida.com/browse/ORANGE-863
https://jira.amida.com/browse/ORANGE-909
Post to `/login` with invalid credentials from postman or Orange-Mobile
Verify it returns a 404
> Fixing 500 from invalid credentials

- server/migrations/20181114172213-userId-refreshToken.js
Add's userId column to refreshToken table as a migration if it doesn't exist. Doesn't undo column if migration is undone (due to the column creation now being in original table creation script)
> add migration for userId on refreshToken table if it doesnt exist

- server/controllers/user.controller.js
- server/migrations/20181114172213-userId-refreshToken.js
This disallows registrar users from creating new registrar users. Only admin can do that.
ORANGE-1017
make sure you're .env has something like this:
```bash
AUTH_SERVICE_PUBLIC_REGISTRATION=false
AUTH_SERVICE_REGISTRAR_SCOPES=["programAdministrator"]
```
As an admin user create a new user with the registrar scope (in this case: `"programAdministrator"`)
```
POST /api/v1/user
{
"username": "PA",
"email": "pa@example.com",
"password": "Password1!",
"scopes": ["programAdministrator"]
}
```
That should work.
Now login as that newly created programAdministrator and try to create a new programAdminstrator using a similar request to above.
That should fail with a descriptive error message.
---
We should also go ahead …
> disallowing registrar scopes to create new users with a registrar or admin scope

- CHANGELOG.md
- src/config/express.js
https://jira.amida.com/browse/SER-275
See Jira ticket.
**Test 1**: `yarn test`, and note that you don't get loads of logging for each test.
**Test 2**: Make an incorrect API call. You should the see the actual error you caused (not always the exact same error, namely "TypeError: Cannot read property 'getAllInfo' of undefined") logged at warn level.
Example incorrect API call:
`POST` to `/api/v2/auth/login` with body
```
{
"username": "something",
"password": "something"
}
```
with an incorrect username and/or incorrect password, and you should get...
**Test 2 Case A**: When `NODE_ENV=development`, you should get logging statement:
`2019-04-08T17:02:17.562Z warn: [object Object]`
Note: This `[object Object]` will be fixed (made readable and useful) by some soon-to-be implemented changes in …
> [SER-275] Replace winston.errorLogger with winston.warn
